### ISSUE TITLE
Add death counter

### ISSUE THREAD

**Issue by dram55** [dram55/MarioMaker2OCR#2]
Detect and keep count of when deaths occur in the video feed. 

Include this death counter to program output.

Design choice: Keep running total or initialize counter on program load?

**Comment by underscore-zi** [comment]
I've built something that does this already for smm1 and 2, also detects start overs, clears and exits.

I haven't put source out because no one seemed interested in it, and I dont k owany people in the smm community, but I can try and work it into what you have here. 

https://www.reddit.com/r/MarioMaker/comments/c6vk8j/automatic_death_counter_for_smm_1_and_2

**Comment by dram55** [comment]
Awesome! I thought about implementing this and I came across your post last night which is what convinced me to try it out. To be honest I'm more interested in doing it to have an excuse to mess with open cv than actually using it the data.

Feel free to implement if you want to take a stab! There are plenty of other things to work on in terms of using open cv. 

If you don't mind, assign the task to yourself if you are working on it just so I know.

**Comment by underscore-zi** [comment]
Do you have any thoughts on the output system I described, and used on the death counter? Having something publishing the events like a websocket may be more extensible than the current system?

**Comment by underscore-zi** [comment]
I'd be happy to work on it, but I won't be home for a few more days so I won't assign it to myself until then.

Messing with opencv was my motive also for the original  base script that countedamd tracked GPBs deaths on Kaozo3. It's a fairly good starter project for opencv
