### ISSUE TITLE
OCR not registering anything when the light in my room is turned on....

### ISSUE THREAD

**Issue by Olphare** [dram55/MarioMaker2OCR#65]
When I have the lights in my room turned on, the OCR doesn't register at all.
When I have the lights turned off it works.
I have a clip from Twitch that shows this.
https://clips.twitch.tv/ArbitraryTsundereVanillaKappaWealth

**Comment by dram55** [comment]
lol this is a new one. Are you using Stream Labs virtual cam? If so, that would explain it, because the virtual cam includes your webcam in the OCR feed - and the lights in your room prevent the program from matching a black screen. We don't fully support SLOBS yet, because of this reason. 

If you are using OBS, then this (hopefully) can be fixed by applying the virtual cam directly on your source (right click source -> Filters) instead of on the entire scene (Tools -> VirtualCam)

**Comment by Olphare** [comment]
Ah, I see. I am using Streamlabs OSB. That explains it. Thank you so much Dram. I'll just have to wait then :)
Keep up the good work! It is a really neat software.
